version: '2'
services:
    moustache-app:
        image: moustache
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://moustache-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=moustache
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moustache-mongodb:
        extends:
            file: mongodb.yml
            service: moustache-mongodb
